# XO Services

- name: ...IS BEGINNING =====================================
  meta: noop

- name: Recording STAGE 5 HAS COMPLETED =====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=5'
