# Generic Apps

- name: ...IS BEGINNING ====================================
  meta: noop

- name: MEDIAWIKI
  include_role:
    name: mediawiki
  when: mediawiki_install

- name: NEXTCLOUD
  include_role:
    name: nextcloud
  when: nextcloud_install

- name: WORDPRESS
  include_role:
    name: wordpress
  when: wordpress_install

- name: Recording STAGE 6 HAS COMPLETED ====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=6'
