# Educational Apps

- name: ...IS BEGINNING ========================================
  meta: noop

- name: KALITE
  include_role:
    name: kalite
  when: kalite_install and (is_ubuntu_2204 or is_ubuntu_2310 or is_debian_12)    # Also covers is_linuxmint_21 and is_raspbian_12

- name: KOLIBRI
  include_role:
    name: kolibri
  when: kolibri_install
  #when: kolibri_install and python_version is version('3.12', '<')    # Debian 13 still uses Python 3.11 (for now!) so really this just avoids Ubuntu 24.04 and 24.10 pre-releases during initial iiab-install.  CLARIF: This is all TEMPORARY until learningequality/kolibri#11316 brings Python 3.12 support to Kolibri 0.17 pre-releases (expected very soon).

- name: KIWIX
  include_role:
    name: kiwix
  when: kiwix_install

- name: MOODLE
  include_role:
    name: moodle
  when: moodle_install

- name: OSM-VECTOR-MAPS
  include_role:
    name: osm-vector-maps
  when: osm_vector_maps_install



- name: SUGARIZER
  include_role:
    name: sugarizer
  when: sugarizer_install and dpkg_arch.stdout is search("64")

- name: Recording STAGE 7 HAS COMPLETED ========================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=7'
