# Local Add-ons

- name: ...IS BEGINNING ====================================
  meta: noop

- name: AZURACAST
  include_role:
    name: azuracast
  when: azuracast_install

# Porting to Python 3 is complete: does this belong elsewhere?
- name: CAPTIVE PORTAL
  include_role:
    name: captiveportal
  when: captiveportal_install

- name: CALIBRE-WEB
  include_role:
    name: calibre-web
  when: calibreweb_install

# KEEP NEAR THE VERY END as this installs dependencies from Debian's 'testing' branch!
- name: CALIBRE
  include_role:
    name: calibre
  when: calibre_install

# Pulls in a large number of devel packages, via asterisk.yml -> 'install_prereq install'
# https://github.com/asterisk/asterisk/blob/master/contrib/scripts/install_prereq#L21-L35
- name: PBX - Asterisk & FreePBX
  include_role:
    name: pbx
  when: pbx_install


- name: '2023-11-05 / TEMPORARY UNTIL ADMIN CONSOLE DECLARES ITS DEPENDENCY: Install MySQL (MariaDB) if admin_console_install (for setup-feedback and record_feedback.php)'
  set_fact:
    mysql_install: True
    mysql_enabled: True
  when: admin_console_install

- name: '2023-11-05 / TEMPORARY UNTIL ADMIN CONSOLE DECLARES ITS DEPENDENCY: Install MySQL (MariaDB) if admin_console_install (for setup-feedback and record_feedback.php)'
  include_role:
    name: mysql
  when: admin_console_install

- name: '2023-11-05 / TEMPORARY UNTIL ADMIN CONSOLE DECLARES ITS DEPENDENCY: Install MySQL (MariaDB) if admin_console_install (for setup-feedback and record_feedback.php)'
  fail:
    msg: "Admin Console install cannot proceed, as MySQL / MariaDB is not installed."
  when: admin_console_install and mysql_installed is undefined


# 2023-11-05: Moved from Stage 8, as it acts on mysql_installed (that might be set just above!)
- name: MUNIN
  include_role:
    name: munin
  when: munin_install


- name: Read 'disk_used_a_priori' from /etc/iiab/iiab.ini
  set_fact:
    df1: "{{ lookup('ansible.builtin.ini', 'disk_used_a_priori', section='summary', file=iiab_ini_file) }}"

- name: Record currently used disk space, to compare with original 'disk_used_a_priori'
  shell: df -B1 --output=used / | tail -1
  register: df2

- name: Add ESTIMATED 'iiab_software_disk_usage = {{ df2.stdout|int - df1|int }}' to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: summary
    option: iiab_software_disk_usage
    value: "{{ df2.stdout|int - df1|int }}"

- name: Recording STAGE 9 HAS COMPLETED ====================
  lineinfile:
    path: "{{ iiab_env_file }}"
    regexp: '^STAGE=*'
    line: 'STAGE=9'
